//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RepoBox.RepoWS_Cancel {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Application", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class CancelSOAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cancel_signatureOperationCompleted;
        
        private System.Threading.SendOrPostCallback query_pending_cancellationOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancel64OperationCompleted;
        
        private System.Threading.SendOrPostCallback get_receiptOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback out_cancelOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CancelSOAP() {
            this.Url = global::RepoBox.Properties.Settings.Default.RepoBox_RepoWS_Cancel_CancelSOAP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cancel_signatureCompletedEventHandler cancel_signatureCompleted;
        
        /// <remarks/>
        public event query_pending_cancellationCompletedEventHandler query_pending_cancellationCompleted;
        
        /// <remarks/>
        public event cancel64CompletedEventHandler cancel64Completed;
        
        /// <remarks/>
        public event get_receiptCompletedEventHandler get_receiptCompleted;
        
        /// <remarks/>
        public event cancelCompletedEventHandler cancelCompleted;
        
        /// <remarks/>
        public event out_cancelCompletedEventHandler out_cancelCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("cancel_signature", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("cancel_signatureResponse", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
        public cancel_signatureResponse cancel_signature([System.Xml.Serialization.XmlElementAttribute("cancel_signature", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")] cancel_signature cancel_signature1) {
            object[] results = this.Invoke("cancel_signature", new object[] {
                        cancel_signature1});
            return ((cancel_signatureResponse)(results[0]));
        }
        
        /// <remarks/>
        public void cancel_signatureAsync(cancel_signature cancel_signature1) {
            this.cancel_signatureAsync(cancel_signature1, null);
        }
        
        /// <remarks/>
        public void cancel_signatureAsync(cancel_signature cancel_signature1, object userState) {
            if ((this.cancel_signatureOperationCompleted == null)) {
                this.cancel_signatureOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncancel_signatureOperationCompleted);
            }
            this.InvokeAsync("cancel_signature", new object[] {
                        cancel_signature1}, this.cancel_signatureOperationCompleted, userState);
        }
        
        private void Oncancel_signatureOperationCompleted(object arg) {
            if ((this.cancel_signatureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancel_signatureCompleted(this, new cancel_signatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("query_pending_cancellation", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("query_pending_cancellationResponse", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
        public query_pending_cancellationResponse query_pending_cancellation([System.Xml.Serialization.XmlElementAttribute("query_pending_cancellation", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")] query_pending_cancellation query_pending_cancellation1) {
            object[] results = this.Invoke("query_pending_cancellation", new object[] {
                        query_pending_cancellation1});
            return ((query_pending_cancellationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void query_pending_cancellationAsync(query_pending_cancellation query_pending_cancellation1) {
            this.query_pending_cancellationAsync(query_pending_cancellation1, null);
        }
        
        /// <remarks/>
        public void query_pending_cancellationAsync(query_pending_cancellation query_pending_cancellation1, object userState) {
            if ((this.query_pending_cancellationOperationCompleted == null)) {
                this.query_pending_cancellationOperationCompleted = new System.Threading.SendOrPostCallback(this.Onquery_pending_cancellationOperationCompleted);
            }
            this.InvokeAsync("query_pending_cancellation", new object[] {
                        query_pending_cancellation1}, this.query_pending_cancellationOperationCompleted, userState);
        }
        
        private void Onquery_pending_cancellationOperationCompleted(object arg) {
            if ((this.query_pending_cancellationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.query_pending_cancellationCompleted(this, new query_pending_cancellationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("cancel64", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("cancel64Response", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
        public cancel64Response cancel64([System.Xml.Serialization.XmlElementAttribute("cancel64", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")] cancel64 cancel641) {
            object[] results = this.Invoke("cancel64", new object[] {
                        cancel641});
            return ((cancel64Response)(results[0]));
        }
        
        /// <remarks/>
        public void cancel64Async(cancel64 cancel641) {
            this.cancel64Async(cancel641, null);
        }
        
        /// <remarks/>
        public void cancel64Async(cancel64 cancel641, object userState) {
            if ((this.cancel64OperationCompleted == null)) {
                this.cancel64OperationCompleted = new System.Threading.SendOrPostCallback(this.Oncancel64OperationCompleted);
            }
            this.InvokeAsync("cancel64", new object[] {
                        cancel641}, this.cancel64OperationCompleted, userState);
        }
        
        private void Oncancel64OperationCompleted(object arg) {
            if ((this.cancel64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancel64Completed(this, new cancel64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("get_receipt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("get_receiptResponse", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
        public get_receiptResponse get_receipt([System.Xml.Serialization.XmlElementAttribute("get_receipt", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")] get_receipt get_receipt1) {
            object[] results = this.Invoke("get_receipt", new object[] {
                        get_receipt1});
            return ((get_receiptResponse)(results[0]));
        }
        
        /// <remarks/>
        public void get_receiptAsync(get_receipt get_receipt1) {
            this.get_receiptAsync(get_receipt1, null);
        }
        
        /// <remarks/>
        public void get_receiptAsync(get_receipt get_receipt1, object userState) {
            if ((this.get_receiptOperationCompleted == null)) {
                this.get_receiptOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_receiptOperationCompleted);
            }
            this.InvokeAsync("get_receipt", new object[] {
                        get_receipt1}, this.get_receiptOperationCompleted, userState);
        }
        
        private void Onget_receiptOperationCompleted(object arg) {
            if ((this.get_receiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_receiptCompleted(this, new get_receiptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("cancel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("cancelResponse", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
        public cancelResponse cancel([System.Xml.Serialization.XmlElementAttribute("cancel", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")] cancel cancel1) {
            object[] results = this.Invoke("cancel", new object[] {
                        cancel1});
            return ((cancelResponse)(results[0]));
        }
        
        /// <remarks/>
        public void cancelAsync(cancel cancel1) {
            this.cancelAsync(cancel1, null);
        }
        
        /// <remarks/>
        public void cancelAsync(cancel cancel1, object userState) {
            if ((this.cancelOperationCompleted == null)) {
                this.cancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelOperationCompleted);
            }
            this.InvokeAsync("cancel", new object[] {
                        cancel1}, this.cancelOperationCompleted, userState);
        }
        
        private void OncancelOperationCompleted(object arg) {
            if ((this.cancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelCompleted(this, new cancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("out_cancel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("out_cancelResponse", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
        public out_cancelResponse out_cancel([System.Xml.Serialization.XmlElementAttribute("out_cancel", Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")] out_cancel out_cancel1) {
            object[] results = this.Invoke("out_cancel", new object[] {
                        out_cancel1});
            return ((out_cancelResponse)(results[0]));
        }
        
        /// <remarks/>
        public void out_cancelAsync(out_cancel out_cancel1) {
            this.out_cancelAsync(out_cancel1, null);
        }
        
        /// <remarks/>
        public void out_cancelAsync(out_cancel out_cancel1, object userState) {
            if ((this.out_cancelOperationCompleted == null)) {
                this.out_cancelOperationCompleted = new System.Threading.SendOrPostCallback(this.Onout_cancelOperationCompleted);
            }
            this.InvokeAsync("out_cancel", new object[] {
                        out_cancel1}, this.out_cancelOperationCompleted, userState);
        }
        
        private void Onout_cancelOperationCompleted(object arg) {
            if ((this.out_cancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.out_cancelCompleted(this, new out_cancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class cancel_signature {
        
        private byte[] xmlField;
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Nullable<bool> store_pendingField;
        
        private bool store_pendingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> store_pending {
            get {
                return this.store_pendingField;
            }
            set {
                this.store_pendingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool store_pendingSpecified {
            get {
                return this.store_pendingFieldSpecified;
            }
            set {
                this.store_pendingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class out_cancelResponse {
        
        private string out_cancelResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string out_cancelResult {
            get {
                return this.out_cancelResultField;
            }
            set {
                this.out_cancelResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class out_cancel {
        
        private byte[] xmlField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string taxpayer_idField;
        
        private byte[] cerField;
        
        private byte[] keyField;
        
        private System.Nullable<bool> store_pendingField;
        
        private bool store_pendingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] cer {
            get {
                return this.cerField;
            }
            set {
                this.cerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> store_pending {
            get {
                return this.store_pendingField;
            }
            set {
                this.store_pendingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool store_pendingSpecified {
            get {
                return this.store_pendingFieldSpecified;
            }
            set {
                this.store_pendingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class cancelResponse {
        
        private CancelaCFDResult cancelResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CancelaCFDResult cancelResult {
            get {
                return this.cancelResultField;
            }
            set {
                this.cancelResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="soap.complex_model")]
    public partial class CancelaCFDResult {
        
        private Folio[] foliosField;
        
        private string acuseField;
        
        private string fechaField;
        
        private string rfcEmisorField;
        
        private string codEstatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Folio[] Folios {
            get {
                return this.foliosField;
            }
            set {
                this.foliosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Acuse {
            get {
                return this.acuseField;
            }
            set {
                this.acuseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                this.rfcEmisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodEstatus {
            get {
                return this.codEstatusField;
            }
            set {
                this.codEstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="soap.complex_model")]
    public partial class Folio {
        
        private string uUIDField;
        
        private string estatusUUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EstatusUUID {
            get {
                return this.estatusUUIDField;
            }
            set {
                this.estatusUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class cancel {
        
        private UUIDS uUIDSField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string taxpayer_idField;
        
        private byte[] cerField;
        
        private byte[] keyField;
        
        private byte[] passllaveField;
        
        private System.Nullable<bool> store_pendingField;
        
        private bool store_pendingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UUIDS UUIDS {
            get {
                return this.uUIDSField;
            }
            set {
                this.uUIDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] cer {
            get {
                return this.cerField;
            }
            set {
                this.cerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] passllave {
            get {
                return this.passllaveField;
            }
            set {
                this.passllaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> store_pending {
            get {
                return this.store_pendingField;
            }
            set {
                this.store_pendingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool store_pendingSpecified {
            get {
                return this.store_pendingFieldSpecified;
            }
            set {
                this.store_pendingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="soap.complex_model")]
    public partial class UUIDS {
        
        private string[] uuidsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
        public string[] uuids {
            get {
                return this.uuidsField;
            }
            set {
                this.uuidsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class get_receiptResponse {
        
        private string get_receiptResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string get_receiptResult {
            get {
                return this.get_receiptResultField;
            }
            set {
                this.get_receiptResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class get_receipt {
        
        private string usernameField;
        
        private string passwordField;
        
        private string taxpayer_idField;
        
        private string uuidField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class cancel64Response {
        
        private CancelaCFDResult cancel64ResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CancelaCFDResult cancel64Result {
            get {
                return this.cancel64ResultField;
            }
            set {
                this.cancel64ResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class cancel64 {
        
        private UUIDS uUIDSField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string taxpayer_idField;
        
        private string cerField;
        
        private string keyField;
        
        private string passllaveField;
        
        private System.Nullable<bool> store_pendingField;
        
        private bool store_pendingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UUIDS UUIDS {
            get {
                return this.uUIDSField;
            }
            set {
                this.uUIDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string taxpayer_id {
            get {
                return this.taxpayer_idField;
            }
            set {
                this.taxpayer_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cer {
            get {
                return this.cerField;
            }
            set {
                this.cerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passllave {
            get {
                return this.passllaveField;
            }
            set {
                this.passllaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> store_pending {
            get {
                return this.store_pendingField;
            }
            set {
                this.store_pendingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool store_pendingSpecified {
            get {
                return this.store_pendingFieldSpecified;
            }
            set {
                this.store_pendingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="query_pending_cancellationResponse", Namespace="soap.complex_model")]
    public partial class query_pending_cancellationResponse1 {
        
        private string xmlField;
        
        private string uuid_statusField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid_status {
            get {
                return this.uuid_statusField;
            }
            set {
                this.uuid_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class query_pending_cancellationResponse {
        
        private query_pending_cancellationResponse1 query_pending_cancellationResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public query_pending_cancellationResponse1 query_pending_cancellationResult {
            get {
                return this.query_pending_cancellationResultField;
            }
            set {
                this.query_pending_cancellationResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class query_pending_cancellation {
        
        private string usernameField;
        
        private string passwordField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://timbrador.cepdi.mx:8443/WSProduccion/WS?WSDL")]
    public partial class cancel_signatureResponse {
        
        private string cancel_signatureResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cancel_signatureResult {
            get {
                return this.cancel_signatureResultField;
            }
            set {
                this.cancel_signatureResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void cancel_signatureCompletedEventHandler(object sender, cancel_signatureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancel_signatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancel_signatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cancel_signatureResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cancel_signatureResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void query_pending_cancellationCompletedEventHandler(object sender, query_pending_cancellationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class query_pending_cancellationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal query_pending_cancellationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public query_pending_cancellationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((query_pending_cancellationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void cancel64CompletedEventHandler(object sender, cancel64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancel64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancel64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cancel64Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cancel64Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_receiptCompletedEventHandler(object sender, get_receiptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_receiptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_receiptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public get_receiptResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((get_receiptResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void cancelCompletedEventHandler(object sender, cancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public cancelResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((cancelResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void out_cancelCompletedEventHandler(object sender, out_cancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class out_cancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal out_cancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public out_cancelResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((out_cancelResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591