//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RepoboxTimbradoDLL.SEFINZacatecas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="facturacionPortBinding", Namespace="http://webservices.finanzas.zacatecas.com/")]
    public partial class facturacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerFacturaGlobalIngresosOperationCompleted;
        
        private System.Threading.SendOrPostCallback guarda_facturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerFacturaGlobalEgresosOperationCompleted;
        
        private System.Threading.SendOrPostCallback factura_siguienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback factura_reciboOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancela_facturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback factura_actualiza_domicilioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public facturacion() {
            this.Url = global::RepoboxTimbradoDLL.Properties.Settings.Default.RepoboxTimbradoDLL_SEFINZacatecas_facturacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerFacturaGlobalIngresosCompletedEventHandler ObtenerFacturaGlobalIngresosCompleted;
        
        /// <remarks/>
        public event guarda_facturaCompletedEventHandler guarda_facturaCompleted;
        
        /// <remarks/>
        public event ObtenerFacturaGlobalEgresosCompletedEventHandler ObtenerFacturaGlobalEgresosCompleted;
        
        /// <remarks/>
        public event factura_siguienteCompletedEventHandler factura_siguienteCompleted;
        
        /// <remarks/>
        public event factura_reciboCompletedEventHandler factura_reciboCompleted;
        
        /// <remarks/>
        public event cancela_facturaCompletedEventHandler cancela_facturaCompleted;
        
        /// <remarks/>
        public event factura_actualiza_domicilioCompletedEventHandler factura_actualiza_domicilioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.finanzas.zacatecas.com/", ResponseNamespace="http://webservices.finanzas.zacatecas.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtenerFacturaGlobalIngresos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FechaIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FechaFin, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfc_dep) {
            object[] results = this.Invoke("ObtenerFacturaGlobalIngresos", new object[] {
                        FechaIni,
                        FechaFin,
                        rfc_dep});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerFacturaGlobalIngresosAsync(string FechaIni, string FechaFin, string rfc_dep) {
            this.ObtenerFacturaGlobalIngresosAsync(FechaIni, FechaFin, rfc_dep, null);
        }
        
        /// <remarks/>
        public void ObtenerFacturaGlobalIngresosAsync(string FechaIni, string FechaFin, string rfc_dep, object userState) {
            if ((this.ObtenerFacturaGlobalIngresosOperationCompleted == null)) {
                this.ObtenerFacturaGlobalIngresosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerFacturaGlobalIngresosOperationCompleted);
            }
            this.InvokeAsync("ObtenerFacturaGlobalIngresos", new object[] {
                        FechaIni,
                        FechaFin,
                        rfc_dep}, this.ObtenerFacturaGlobalIngresosOperationCompleted, userState);
        }
        
        private void OnObtenerFacturaGlobalIngresosOperationCompleted(object arg) {
            if ((this.ObtenerFacturaGlobalIngresosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerFacturaGlobalIngresosCompleted(this, new ObtenerFacturaGlobalIngresosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.finanzas.zacatecas.com/", ResponseNamespace="http://webservices.finanzas.zacatecas.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public estatus guarda_factura([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int clave, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool claveSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int no_factura, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool no_facturaSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tipo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfc_dep) {
            object[] results = this.Invoke("guarda_factura", new object[] {
                        clave,
                        claveSpecified,
                        no_factura,
                        no_facturaSpecified,
                        tipo,
                        rfc_dep});
            return ((estatus)(results[0]));
        }
        
        /// <remarks/>
        public void guarda_facturaAsync(int clave, bool claveSpecified, int no_factura, bool no_facturaSpecified, string tipo, string rfc_dep) {
            this.guarda_facturaAsync(clave, claveSpecified, no_factura, no_facturaSpecified, tipo, rfc_dep, null);
        }
        
        /// <remarks/>
        public void guarda_facturaAsync(int clave, bool claveSpecified, int no_factura, bool no_facturaSpecified, string tipo, string rfc_dep, object userState) {
            if ((this.guarda_facturaOperationCompleted == null)) {
                this.guarda_facturaOperationCompleted = new System.Threading.SendOrPostCallback(this.Onguarda_facturaOperationCompleted);
            }
            this.InvokeAsync("guarda_factura", new object[] {
                        clave,
                        claveSpecified,
                        no_factura,
                        no_facturaSpecified,
                        tipo,
                        rfc_dep}, this.guarda_facturaOperationCompleted, userState);
        }
        
        private void Onguarda_facturaOperationCompleted(object arg) {
            if ((this.guarda_facturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guarda_facturaCompleted(this, new guarda_facturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.finanzas.zacatecas.com/", ResponseNamespace="http://webservices.finanzas.zacatecas.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtenerFacturaGlobalEgresos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FechaIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FechaFin, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfc_dep) {
            object[] results = this.Invoke("ObtenerFacturaGlobalEgresos", new object[] {
                        FechaIni,
                        FechaFin,
                        rfc_dep});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerFacturaGlobalEgresosAsync(string FechaIni, string FechaFin, string rfc_dep) {
            this.ObtenerFacturaGlobalEgresosAsync(FechaIni, FechaFin, rfc_dep, null);
        }
        
        /// <remarks/>
        public void ObtenerFacturaGlobalEgresosAsync(string FechaIni, string FechaFin, string rfc_dep, object userState) {
            if ((this.ObtenerFacturaGlobalEgresosOperationCompleted == null)) {
                this.ObtenerFacturaGlobalEgresosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerFacturaGlobalEgresosOperationCompleted);
            }
            this.InvokeAsync("ObtenerFacturaGlobalEgresos", new object[] {
                        FechaIni,
                        FechaFin,
                        rfc_dep}, this.ObtenerFacturaGlobalEgresosOperationCompleted, userState);
        }
        
        private void OnObtenerFacturaGlobalEgresosOperationCompleted(object arg) {
            if ((this.ObtenerFacturaGlobalEgresosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerFacturaGlobalEgresosCompleted(this, new ObtenerFacturaGlobalEgresosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.finanzas.zacatecas.com/", ResponseNamespace="http://webservices.finanzas.zacatecas.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tSiguienteFactura factura_siguiente() {
            object[] results = this.Invoke("factura_siguiente", new object[0]);
            return ((tSiguienteFactura)(results[0]));
        }
        
        /// <remarks/>
        public void factura_siguienteAsync() {
            this.factura_siguienteAsync(null);
        }
        
        /// <remarks/>
        public void factura_siguienteAsync(object userState) {
            if ((this.factura_siguienteOperationCompleted == null)) {
                this.factura_siguienteOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfactura_siguienteOperationCompleted);
            }
            this.InvokeAsync("factura_siguiente", new object[0], this.factura_siguienteOperationCompleted, userState);
        }
        
        private void Onfactura_siguienteOperationCompleted(object arg) {
            if ((this.factura_siguienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.factura_siguienteCompleted(this, new factura_siguienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.finanzas.zacatecas.com/", ResponseNamespace="http://webservices.finanzas.zacatecas.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string factura_recibo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int folio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool folioSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tipo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Fecha, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfc_dep) {
            object[] results = this.Invoke("factura_recibo", new object[] {
                        folio,
                        folioSpecified,
                        tipo,
                        Fecha,
                        rfc_dep});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void factura_reciboAsync(int folio, bool folioSpecified, string tipo, string Fecha, string rfc_dep) {
            this.factura_reciboAsync(folio, folioSpecified, tipo, Fecha, rfc_dep, null);
        }
        
        /// <remarks/>
        public void factura_reciboAsync(int folio, bool folioSpecified, string tipo, string Fecha, string rfc_dep, object userState) {
            if ((this.factura_reciboOperationCompleted == null)) {
                this.factura_reciboOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfactura_reciboOperationCompleted);
            }
            this.InvokeAsync("factura_recibo", new object[] {
                        folio,
                        folioSpecified,
                        tipo,
                        Fecha,
                        rfc_dep}, this.factura_reciboOperationCompleted, userState);
        }
        
        private void Onfactura_reciboOperationCompleted(object arg) {
            if ((this.factura_reciboCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.factura_reciboCompleted(this, new factura_reciboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.finanzas.zacatecas.com/", ResponseNamespace="http://webservices.finanzas.zacatecas.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public estatus cancela_factura([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string foliofactura, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string seriefactura, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string motivo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfc_dep) {
            object[] results = this.Invoke("cancela_factura", new object[] {
                        foliofactura,
                        seriefactura,
                        motivo,
                        rfc_dep});
            return ((estatus)(results[0]));
        }
        
        /// <remarks/>
        public void cancela_facturaAsync(string foliofactura, string seriefactura, string motivo, string rfc_dep) {
            this.cancela_facturaAsync(foliofactura, seriefactura, motivo, rfc_dep, null);
        }
        
        /// <remarks/>
        public void cancela_facturaAsync(string foliofactura, string seriefactura, string motivo, string rfc_dep, object userState) {
            if ((this.cancela_facturaOperationCompleted == null)) {
                this.cancela_facturaOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncancela_facturaOperationCompleted);
            }
            this.InvokeAsync("cancela_factura", new object[] {
                        foliofactura,
                        seriefactura,
                        motivo,
                        rfc_dep}, this.cancela_facturaOperationCompleted, userState);
        }
        
        private void Oncancela_facturaOperationCompleted(object arg) {
            if ((this.cancela_facturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancela_facturaCompleted(this, new cancela_facturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.finanzas.zacatecas.com/", ResponseNamespace="http://webservices.finanzas.zacatecas.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public estatus factura_actualiza_domicilio([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string calle, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string numeroext, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string numeroint, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string colonia, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string municipiodeleg, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ciudad, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string estado, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pais, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string correo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int clave, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool claveSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfc_dep) {
            object[] results = this.Invoke("factura_actualiza_domicilio", new object[] {
                        rfc,
                        calle,
                        numeroext,
                        numeroint,
                        colonia,
                        municipiodeleg,
                        ciudad,
                        estado,
                        pais,
                        correo,
                        clave,
                        claveSpecified,
                        rfc_dep});
            return ((estatus)(results[0]));
        }
        
        /// <remarks/>
        public void factura_actualiza_domicilioAsync(string rfc, string calle, string numeroext, string numeroint, string colonia, string municipiodeleg, string ciudad, string estado, string pais, string correo, int clave, bool claveSpecified, string rfc_dep) {
            this.factura_actualiza_domicilioAsync(rfc, calle, numeroext, numeroint, colonia, municipiodeleg, ciudad, estado, pais, correo, clave, claveSpecified, rfc_dep, null);
        }
        
        /// <remarks/>
        public void factura_actualiza_domicilioAsync(string rfc, string calle, string numeroext, string numeroint, string colonia, string municipiodeleg, string ciudad, string estado, string pais, string correo, int clave, bool claveSpecified, string rfc_dep, object userState) {
            if ((this.factura_actualiza_domicilioOperationCompleted == null)) {
                this.factura_actualiza_domicilioOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfactura_actualiza_domicilioOperationCompleted);
            }
            this.InvokeAsync("factura_actualiza_domicilio", new object[] {
                        rfc,
                        calle,
                        numeroext,
                        numeroint,
                        colonia,
                        municipiodeleg,
                        ciudad,
                        estado,
                        pais,
                        correo,
                        clave,
                        claveSpecified,
                        rfc_dep}, this.factura_actualiza_domicilioOperationCompleted, userState);
        }
        
        private void Onfactura_actualiza_domicilioOperationCompleted(object arg) {
            if ((this.factura_actualiza_domicilioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.factura_actualiza_domicilioCompleted(this, new factura_actualiza_domicilioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.finanzas.zacatecas.com/")]
    public partial class estatus {
        
        private string errorField;
        
        private int estatus1Field;
        
        private bool estatus1FieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("estatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int estatus1 {
            get {
                return this.estatus1Field;
            }
            set {
                this.estatus1Field = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estatus1Specified {
            get {
                return this.estatus1FieldSpecified;
            }
            set {
                this.estatus1FieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.finanzas.zacatecas.com/")]
    public partial class tSiguienteFactura {
        
        private int folioField;
        
        private bool folioFieldSpecified;
        
        private string tipoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool folioSpecified {
            get {
                return this.folioFieldSpecified;
            }
            set {
                this.folioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerFacturaGlobalIngresosCompletedEventHandler(object sender, ObtenerFacturaGlobalIngresosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerFacturaGlobalIngresosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerFacturaGlobalIngresosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void guarda_facturaCompletedEventHandler(object sender, guarda_facturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guarda_facturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guarda_facturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public estatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((estatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ObtenerFacturaGlobalEgresosCompletedEventHandler(object sender, ObtenerFacturaGlobalEgresosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerFacturaGlobalEgresosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerFacturaGlobalEgresosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void factura_siguienteCompletedEventHandler(object sender, factura_siguienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class factura_siguienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal factura_siguienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tSiguienteFactura Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tSiguienteFactura)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void factura_reciboCompletedEventHandler(object sender, factura_reciboCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class factura_reciboCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal factura_reciboCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void cancela_facturaCompletedEventHandler(object sender, cancela_facturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancela_facturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancela_facturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public estatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((estatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void factura_actualiza_domicilioCompletedEventHandler(object sender, factura_actualiza_domicilioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class factura_actualiza_domicilioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal factura_actualiza_domicilioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public estatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((estatus)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591